FROM mysql

ENV MYSQL_ROOT_PASSWORD secretcisco
ENV MYSQL_USER=viper
ENV MYSQL_PASSWORD=viper
ENV MYSQL_DATABASE=db_viper

#RUN echo "create database `db_viper`" | mysql -u root -p${MYSQL_ROOT_PASSWORD}
#RUN echo "CREATE USER 'viper'@'%' IDENTIFIED BY 'viper' | mysql -u root -p${MYSQL_ROOT_PASSWORD}
#RUN echo "GRANT ALL PRIVILEGES ON db_viper.* to 'viper'@'%' | mysql -u root -p${MYSQL_ROOT_PASSWORD}
